os: Visual Studio 2019

platform:
  - x64

services:
  - mysql

configuration:
  #- Debug
  - Release

matrix:
  fast_finish: true

build_script:
  - cmake --version
  - SET PATH=%PATH%;"C:\Program Files\MySQL\MySQL Server 5.7\bin"
  - set MYSQL_PWD=Password12!
  - SET
  - mysql -e "create database sqlpp_mysql;" --user=root
  - CD
  - cd ..
  - CD
  #- git clone https://github.com/MariaDB/mariadb-connector-c
  #- cd mariadb-connector-c
  #- mkdir build
  #- cd build
  #- cmake .. -DCMAKE_GENERATOR_PLATFORM=x64
  #- cmake --build . --config %configuration% --target install
  #- CD ..
  #- CD ..
  - CD
  - git clone https://github.com/HowardHinnant/date
  - cd date
  - git checkout tags/v3.0.1
  - mkdir build && mkdir prefix
  - cmake -S . -B build -D CMAKE_INSTALL_PREFIX=%cd%\prefix -D BUILD_TZ_LIB=OFF
  - cmake --build build --target install
  - cd ..
  - git clone https://github.com/rbock/sqlpp11
  - cd sqlpp11
  - git checkout tags/0.60
  - mkdir build && mkdir prefix
  - cmake -S . -B build -D CMAKE_INSTALL_PREFIX=%cd%\prefix
  - cmake --build build --target install
  - cd ..
  - cd sqlpp11-connector-mysql
  - CD
  - echo %configuration%
  - mkdir build && mkdir prefix
  - cmake -S . -D CMAKE_BUILD_TYPE=%configuration% -D CMAKE_PREFIX_PATH="%cd%/../sqlpp11/prefix;%cd%/../date/prefix" -D CMAKE_INSTALL_PREFIX=`pwd`/prefix -D CMAKE_VERBOSE_MAKEFILE=ON -D CMAKE_CXX_FLAGS="/EHsc /wd4503" -D CMAKE_GENERATOR_PLATFORM=%platform%
  - cmake --build . --config %configuration% --target install
  #- ctest . --output-on-failure --build-config %configuration%
