language: cpp

os:
  - linux

sudo: required
dist: focal

services:
  - mysql

addons:
  apt:
    packages:
    #- mysql-server-5.6
    #- mysql-client-core-5.6
    #- mysql-client-5.6
    - libboost-dev

compiler:
  - clang
  - gcc

env:
  - CONFIG=Release
  #- CONFIG=Debug

notifications:
 email:
   on_success: change
   on_failure: always

install:
  - pwd
  - PROJECT_DIR="$PWD"
  - BRANCH=`git rev-parse --abbrev-ref HEAD`
  - cd ..
  - pwd
  - git clone https://github.com/HowardHinnant/date
  - cd date
  - git checkout tags/v3.0.1
  - mkdir build && mkdir prefix
  - >
    cmake \
      -S . \
      -B build \
      -D CMAKE_INSTALL_PREFIX=`pwd`/prefix \
      -D BUILD_TZ_LIB=OFF
  - cmake --build build --target install
  - cd ..
  - git clone https://github.com/rbock/sqlpp11
  - cd sqlpp11
  - git checkout tags/0.60
  - mkdir build && mkdir prefix
  - >
    cmake \
      -S . \
      -B build \
      -D CMAKE_INSTALL_PREFIX=`pwd`/prefix \
      -D BUILD_TESTING=OFF
  - cmake --build build --target install
  - cd ..
  - mysql --version
  - (while !  mysqladmin -u root status ; do sleep 1; done) # wait for mysql to start
  - mysqladmin -u root create sqlpp_mysql
  - cd "$PROJECT_DIR"

before_script:
   - mkdir build && mkdir prefix
   - if [[ "$CXX" = "g++" && "$CONFIG" = "Debug" && "$TRAVIS_OS_NAME" = "linux" ]]; then export CXXFLAGS="--coverage"; fi
   - >
     cmake \
       -S . \
       -B build \
       -D CMAKE_BUILD_TYPE=$CONFIG \
       -D CMAKE_PREFIX_PATH="`pwd`/../sqlpp11/prefix;`pwd`/../date/prefix" \
       -D CMAKE_INSTALL_PREFIX=`pwd`/prefix \
       -D CMAKE_VERBOSE_MAKEFILE=ON

script:
   - cmake --build build --target install
   - ctest --output-on-failure

after_script:
  - ../coveralls
